/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Farmacia.Empleado;
import Farmacia.Farmacia;
import Farmacia.RegistroClientes;
import java.awt.event.KeyEvent;
import java.util.HashSet;
import javax.swing.JFrame;

/**
 *
 * @author Kevin
 */
public class Login extends javax.swing.JFrame {

    Farmacia farmacia1 = new Farmacia("Trujillo", "California", "2334", "044585696", "0001");
//    Empleado gerente1 = new Empleado("75594802", "Gerente", "ASD", "989599858", "asd@asd.com", true, 5000, farmacia1);
    RegistroClientes registroClientes = new RegistroClientes();
    Empleado actual = null;

    /**
     * Creates new form LOGIN
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
//        registroClientes.agregarPersona("00000000", "Client");
//        gerente1.agregarEmpleado("12345678", "Empleado", "ASD", "989599858", "asd@asd.com", true, 5000, farmacia1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        btnlogin = new javax.swing.JLabel();
        dniLogin = new javax.swing.JTextField();
        settingsButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setLocation(new java.awt.Point(0, 0));
        setMinimumSize(new java.awt.Dimension(715, 476));
        setSize(new java.awt.Dimension(0, 0));
        getContentPane().setLayout(null);

        btnlogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnloginMouseClicked(evt);
            }
        });
        getContentPane().add(btnlogin);
        btnlogin.setBounds(501, 331, 148, 40);

        dniLogin.setBackground(null);
        dniLogin.setFont(new java.awt.Font("Arial Narrow", 1, 16)); // NOI18N
        dniLogin.setForeground(new java.awt.Color(204, 204, 204));
        dniLogin.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        dniLogin.setToolTipText("");
        dniLogin.setBorder(null);
        dniLogin.setCaretColor(new java.awt.Color(255, 255, 255));
        dniLogin.setOpaque(false);
        dniLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dniLoginActionPerformed(evt);
            }
        });
        dniLogin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dniLoginKeyTyped(evt);
            }
        });
        getContentPane().add(dniLogin);
        dniLogin.setBounds(460, 235, 218, 30);

        settingsButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/engranaje (1).png"))); // NOI18N
        settingsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsButtonMouseClicked(evt);
            }
        });
        getContentPane().add(settingsButton);
        settingsButton.setBounds(650, 20, 40, 32);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/Web 1280 – 1.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 700, 440);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dniLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dniLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dniLoginActionPerformed

    private void btnloginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnloginMouseClicked

        String dni = dniLogin.getText();
        actual = farmacia1.login(dni);
        if (actual != null) {
            Menu menu = new Menu(farmacia1, actual, registroClientes);
            menu.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnloginMouseClicked

    private void dniLoginKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dniLoginKeyTyped
        char key = evt.getKeyChar();

        if (key == KeyEvent.VK_ENTER) {
            String dni = dniLogin.getText();
            actual = farmacia1.login(dni);
            if (actual != null) {
                Menu menu = new Menu(farmacia1, actual, registroClientes);
                menu.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_dniLoginKeyTyped

    private void settingsButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsButtonMouseClicked
//        configuraciones
    }//GEN-LAST:event_settingsButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnlogin;
    private javax.swing.JTextField dniLogin;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel settingsButton;
    // End of variables declaration//GEN-END:variables
}
