/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Gui;

import Farmacia.Empleado;
import Farmacia.Farmacia;
import Farmacia.RegistroClientes;
import java.awt.Color;
import java.util.ArrayList;
import Panels.CambiaPanel;


/**
 *
 * @author Kevin
 */
public class Menu extends javax.swing.JFrame {
    
   Farmacia farmacia;
   Empleado actual;
   RegistroClientes registroClientes;
   
   private ArrayList<Farmacia> farmacias;
   
   ArrayList<String> validador;
    /**
     * Creates new form MENU
     */
    public Menu(Farmacia farmacia, Empleado actual, RegistroClientes registroClientes) {
        this.farmacia = farmacia;
        this.actual = actual;
        this.registroClientes=registroClientes;
        initComponents();
        setLocationRelativeTo(null);
        if(actual.getCargo().equalsIgnoreCase("Cajero")){
            uno.setVisible(false);
            dos.setVisible(false);
        }
        if(actual.getCargo().equalsIgnoreCase("Asistente")){
            uno.setVisible(false);
        }
    }
    
    public Menu() {
        initComponents();
        setLocationRelativeTo(null);
        new CambiaPanel(pnlPrincipal,new Panels.panelHome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMenu = new javax.swing.JButton();
        pnlPrincipal = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        uno = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        dos = new javax.swing.JButton();
        cuatro = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1015, 738));
        getContentPane().setLayout(null);

        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_menu_squared_50px.png"))); // NOI18N
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenu);
        btnMenu.setBounds(0, 5, 50, 50);

        pnlPrincipal.setBackground(new java.awt.Color(27, 37, 69));
        getContentPane().add(pnlPrincipal);
        pnlPrincipal.setBounds(290, 0, 710, 700);

        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0,100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        uno.setBackground(new java.awt.Color(0, 0, 0, 150));
        uno.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        uno.setForeground(new java.awt.Color(255, 255, 255));
        uno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_home_24px.png"))); // NOI18N
        uno.setText("Nueva Sede");
        uno.setBorder(null);
        uno.setContentAreaFilled(false);
        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        uno.setRequestFocusEnabled(false);
        uno.setRolloverEnabled(false);
        uno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoActionPerformed(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 430, 290, 40));

        tres.setBackground(new java.awt.Color(102, 153, 255, 100));
        tres.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        tres.setForeground(new java.awt.Color(255, 255, 255));
        tres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_speaker_notes_24px.png"))); // NOI18N
        tres.setText("Registrar Medicamento");
        tres.setBorder(null);
        tres.setContentAreaFilled(false);
        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.setFocusPainted(false);
        tres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        tres.setRequestFocusEnabled(false);
        tres.setRolloverEnabled(false);
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 290, 40));

        dos.setBackground(new java.awt.Color(102, 153, 255, 100));
        dos.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        dos.setForeground(new java.awt.Color(255, 255, 255));
        dos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_worker_26px.png"))); // NOI18N
        dos.setText("Nuevo Empleado");
        dos.setBorder(null);
        dos.setContentAreaFilled(false);
        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.setFocusPainted(false);
        dos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dos.setRequestFocusEnabled(false);
        dos.setRolloverEnabled(false);
        dos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosActionPerformed(evt);
            }
        });
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 290, 40));

        cuatro.setBackground(new java.awt.Color(102, 153, 255,100));
        cuatro.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cuatro.setForeground(new java.awt.Color(255, 255, 255));
        cuatro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_spiral_bound_booklet_24px_1.png"))); // NOI18N
        cuatro.setText("Tomar Pedido");
        cuatro.setBorder(null);
        cuatro.setContentAreaFilled(false);
        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cuatro.setRequestFocusEnabled(false);
        cuatro.setRolloverEnabled(false);
        cuatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroActionPerformed(evt);
            }
        });
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 290, 40));

        cinco.setBackground(new java.awt.Color(102, 153, 255, 100));
        cinco.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cinco.setForeground(new java.awt.Color(255, 255, 255));
        cinco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_coins_32px.png"))); // NOI18N
        cinco.setText("Cuadrar Caja");
        cinco.setBorder(null);
        cinco.setContentAreaFilled(false);
        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        cinco.setRequestFocusEnabled(false);
        cinco.setRolloverEnabled(false);
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 290, 40));

        seis.setBackground(new java.awt.Color(102, 153, 255,100));
        seis.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        seis.setForeground(new java.awt.Color(255, 255, 255));
        seis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_client_management_30px.png"))); // NOI18N
        seis.setText("Agregar Cliente");
        seis.setBorder(null);
        seis.setContentAreaFilled(false);
        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        seis.setRequestFocusEnabled(false);
        seis.setRolloverEnabled(false);
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 290, 40));

        panelMenu.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 700));

        getContentPane().add(panelMenu);
        panelMenu.setBounds(-300, 0, 290, 700);

        jLabel1.setBackground(new java.awt.Color(27, 37, 69));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/MENU FINAK.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void unoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoActionPerformed
        
        new CambiaPanel(pnlPrincipal,new Panels.Sede(farmacias));
    }//GEN-LAST:event_unoActionPerformed

    private void dosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal,new Panels.MenuEmpleado(actual, farmacia));
    }//GEN-LAST:event_dosActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed

        int posi = btnMenu.getX();
        if(posi > 5){
            Animacion.Animacion.mover_izquierda(0, -300, 2, 2, panelMenu);
            Animacion.Animacion.mover_izquierda(295, 0, 2, 2, btnMenu);
        }
        else{
            Animacion.Animacion.mover_derecha(-300, 0, 2, 2, panelMenu);
            Animacion.Animacion.mover_derecha(0, 235, 2, 2, btnMenu);
        }
    }//GEN-LAST:event_btnMenuActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal,new Panels.AgregarCliente(registroClientes,validador));
    }//GEN-LAST:event_seisActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
        farmacia.getR_ventas().actualizarLista();
        new CambiaPanel(pnlPrincipal,new Panels.CuadrarCaja(farmacia));
        
        
    }//GEN-LAST:event_cincoActionPerformed

    private void cuatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroActionPerformed
        // TODO add your handling code here:
        farmacia.getInventario().actualizarLista();
        new CambiaPanel(pnlPrincipal,new Panels.TomarPedido(actual, farmacia, registroClientes));
    }//GEN-LAST:event_cuatroActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(pnlPrincipal,new Panels.MenuMedicamento(actual, farmacia));
    }//GEN-LAST:event_tresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton cinco;
    private javax.swing.JButton cuatro;
    private javax.swing.JButton dos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel panelMenu;
    public static javax.swing.JPanel pnlPrincipal;
    private javax.swing.JButton seis;
    private javax.swing.JButton tres;
    private javax.swing.JButton uno;
    // End of variables declaration//GEN-END:variables
}
