/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import static Gui.Menu.pnlPrincipal;
import Farmacia.Empresa;
import Farmacia.Farmacia;
import Farmacia.Persona;
import Farmacia.Empleado;
import Farmacia.RegistroClientes;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kevin
 */
public class ClientesRegistrados extends javax.swing.JPanel {

    //Listas de clientes
    DefaultListModel modelListPersonas = new DefaultListModel();
    DefaultListModel modelListEmpresas = new DefaultListModel();
    
    RegistroClientes registroClientes;
    
    Empleado actual;
    Farmacia farmacia;
    //validadores
    ArrayList<String> validador;
    /**
     * Creates new form panelCuatroListado
     */
    public ClientesRegistrados(RegistroClientes registroClientes, ArrayList<String> validador) {
        this.registroClientes = registroClientes;
        this.validador = validador;
        initComponents();
        //set listas
        modelListPersonas=new DefaultListModel();
        listaPersonas.setModel(modelListPersonas);
        modelListEmpresas=new DefaultListModel();
        listaEmpresas.setModel(modelListEmpresas);
        //se obtiene los datos de los registros
        obtenerListaPersonas(registroClientes.getPersonas());
        obtenerListaEmpresas(registroClientes.getEmpresas());
    }
    
    public ClientesRegistrados() {
        initComponents();
        modelListPersonas=new DefaultListModel();
        listaPersonas.setModel(modelListPersonas);
        modelListEmpresas=new DefaultListModel();
        listaEmpresas.setModel(modelListEmpresas);
        modelListPersonas.addElement("75594802 ");
        
    }
    
    private void obtenerListaPersonas(ArrayList<Persona> personas) {
        for (int i = 0; i < personas.size(); i++) {
            modelListPersonas.addElement(personas.get(i).getDni() + "    "+personas.get(i).getNombre()+ "    "+personas.get(i).getPuntos());
        }
        if (personas.isEmpty()) {
            modelListPersonas.addElement("No hay personas registradas.");
        }
    }
    private void obtenerListaEmpresas(ArrayList<Empresa> empresas) {
        for (int i = 0; i < empresas.size(); i++) {
            modelListEmpresas.addElement(empresas.get(i).getRuc() + "    "+empresas.get(i).getNombre()+ "    "+empresas.get(i).getPuntos());
        }
        if (empresas.isEmpty()) {
            modelListEmpresas.addElement("No hay personas registradas.");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelClienteRegistro = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listaPersonas = new javax.swing.JList<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaEmpresas = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        seleccionarPersonaButton = new javax.swing.JButton();
        seleccionarEmpresaButton = new javax.swing.JButton();
        inDni = new javax.swing.JTextField();
        inRuc = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        buscarRucButton = new javax.swing.JButton();
        buscarDniButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        setMinimumSize(new java.awt.Dimension(700, 700));
        setPreferredSize(new java.awt.Dimension(700, 700));

        panelClienteRegistro.setBackground(new java.awt.Color(27, 37, 69));
        panelClienteRegistro.setPreferredSize(new java.awt.Dimension(700, 700));

        listaPersonas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(listaPersonas);

        listaEmpresas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaEmpresas);

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CLIENTES REGISTRADOS");
        jLabel1.setToolTipText("");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PERSONAS");

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EMPRESAS");

        seleccionarPersonaButton.setText("Seleccionar");
        seleccionarPersonaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarPersonaButtonActionPerformed(evt);
            }
        });

        seleccionarEmpresaButton.setText("Seleccionar");
        seleccionarEmpresaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarEmpresaButtonActionPerformed(evt);
            }
        });

        inDni.setBackground(new java.awt.Color(27, 37, 69));
        inDni.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        inDni.setForeground(new java.awt.Color(255, 255, 255));
        inDni.setToolTipText("");
        inDni.setBorder(null);
        inDni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inDniActionPerformed(evt);
            }
        });

        inRuc.setBackground(new java.awt.Color(27, 37, 69));
        inRuc.setFont(new java.awt.Font("Arial Narrow", 0, 14)); // NOI18N
        inRuc.setForeground(new java.awt.Color(255, 255, 255));
        inRuc.setToolTipText("");
        inRuc.setBorder(null);
        inRuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inRucActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("DNI");

        buscarRucButton.setText("Buscar:");
        buscarRucButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarRucButtonActionPerformed(evt);
            }
        });

        buscarDniButton.setText("Buscar:");
        buscarDniButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarDniButtonActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("RUC");

        javax.swing.GroupLayout panelClienteRegistroLayout = new javax.swing.GroupLayout(panelClienteRegistro);
        panelClienteRegistro.setLayout(panelClienteRegistroLayout);
        panelClienteRegistroLayout.setHorizontalGroup(
            panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(142, 142, 142))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteRegistroLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(seleccionarPersonaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(seleccionarEmpresaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteRegistroLayout.createSequentialGroup()
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(buscarDniButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(buscarRucButton)
                                .addGap(89, 89, 89))
                            .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(inDni, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(jLabel5))
                                .addGap(131, 131, 131)
                                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator2)
                                    .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                                        .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(inRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
            .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteRegistroLayout.setVerticalGroup(
            panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(seleccionarEmpresaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccionarPersonaButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(83, 83, 83)
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteRegistroLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(inRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteRegistroLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inDni, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelClienteRegistroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buscarDniButton)
                    .addComponent(buscarRucButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelClienteRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buscarDniButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarDniButtonActionPerformed
        Persona persona=registroClientes.buscarPersona(inDni.getText());
        if(persona!=null){
            validador.set(1,persona.getDni());
            validador.set(0, "persona");
            this.setVisible(false);
        }
    }//GEN-LAST:event_buscarDniButtonActionPerformed

    private void buscarRucButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarRucButtonActionPerformed
        Empresa empresa=registroClientes.buscarEmpresa(inRuc.getText());
        if(empresa!=null){
            validador.set(1,empresa.getRuc());
            validador.set(0, "empresa");
            this.setVisible(false);
        }
    }//GEN-LAST:event_buscarRucButtonActionPerformed

    private void inRucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inRucActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inRucActionPerformed

    private void inDniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inDniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inDniActionPerformed

    private void seleccionarEmpresaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarEmpresaButtonActionPerformed
        String ruc;
        if(listaEmpresas.getSelectedValue()!=null){
            ruc=listaEmpresas.getSelectedValue().substring(0,listaEmpresas.getSelectedValue().indexOf(" "));
            validador.set(1,ruc);
            validador.set(0, "empresa");
            System.out.println(ruc+"R-empresa");
            this.setVisible(false);
        }
    }//GEN-LAST:event_seleccionarEmpresaButtonActionPerformed

    private void seleccionarPersonaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarPersonaButtonActionPerformed
        String dni;
        if(listaPersonas.getSelectedValue()!=null){
            dni=listaPersonas.getSelectedValue().substring(0,listaPersonas.getSelectedValue().indexOf(" "));
            validador.set(1,dni);
            validador.set(0, "persona");
            System.out.println(dni+"D- persona");
            this.setVisible(false);
        }
    }//GEN-LAST:event_seleccionarPersonaButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarDniButton;
    private javax.swing.JButton buscarRucButton;
    private javax.swing.JTextField inDni;
    private javax.swing.JTextField inRuc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JList<String> listaEmpresas;
    private javax.swing.JList<String> listaPersonas;
    private javax.swing.JPanel panelClienteRegistro;
    private javax.swing.JButton seleccionarEmpresaButton;
    private javax.swing.JButton seleccionarPersonaButton;
    // End of variables declaration//GEN-END:variables
}
