/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import static Gui.Menu.pnlPrincipal;
import Farmacia.Farmacia;
import Farmacia.Empleado;
import Gui.Menu;
import java.awt.event.KeyEvent;

/**
 *
 * @author Kevin
 */
public class ListaEmpleados extends javax.swing.JPanel {

    private Farmacia farmacia;
    Empleado actual;

    public ListaEmpleados() {
        initComponents();
    }

    public ListaEmpleados(Farmacia farmacia) {
        this.farmacia = farmacia;
        initComponents();
        actualizarTabla();
        

    }
    private void actualizarTabla(){
        int tam = farmacia.getR_empleados().getEmpleados().size();
        String matriz[][] = new String[tam][5];
        for (int i = 0; i < tam; i++) {
            matriz[i][0] = farmacia.getR_empleados().getEmpleados().get(i).getDni();
            matriz[i][1] = farmacia.getR_empleados().getEmpleados().get(i).getNombre();
            matriz[i][2] = farmacia.getR_empleados().getEmpleados().get(i).getCargo();
            matriz[i][3] = farmacia.getR_empleados().getEmpleados().get(i).getTelefono();
            matriz[i][4] = String.valueOf(farmacia.getR_empleados().getEmpleados().get(i).getSueldo());

        }

        tabla.setModel(new javax.swing.table.DefaultTableModel(
                matriz,
                new String[]{
                    "DNI", "Nombre", "Cargo", "Telefono", "Sueldo"
                }
        ));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        eliminarButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        inCodigo = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnIngresarE1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(27, 37, 69));
        setMinimumSize(new java.awt.Dimension(700, 700));

        eliminarButton.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        eliminarButton.setForeground(new java.awt.Color(255, 255, 255));
        eliminarButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        eliminarButton.setText("Eliminar");
        eliminarButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        eliminarButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        eliminarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarButtonMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LISTA DE");

        inCodigo.setBackground(new java.awt.Color(27, 37, 69));
        inCodigo.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        inCodigo.setForeground(new java.awt.Color(255, 255, 255));
        inCodigo.setBorder(null);
        inCodigo.setOpaque(false);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Cargo", "Telefono", "Sueldo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabla.setRowHeight(30);
        tabla.setSelectionBackground(new java.awt.Color(255, 51, 51));
        tabla.setShowVerticalLines(false);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tablaPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tabla);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/persona100.png"))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMPLEADOS");

        btnIngresarE1.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnIngresarE1.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresarE1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnIngresarE1.setText("ACEPTAR");
        btnIngresarE1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnIngresarE1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngresarE1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIngresarE1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel3)
                .addGap(150, 150, 150)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jLabel2))
                    .addComponent(jLabel4)))
            .addComponent(inCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(btnIngresarE1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95)
                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(325, 325, 325)
                        .addComponent(inCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnIngresarE1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(eliminarButton))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void eliminarButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarButtonMouseClicked
        try {
            if (tabla.getSelectedRow() >= 0 && tabla.getSelectedColumn() > 0) {
                farmacia.getR_empleados().eliminarEmpleado(tabla.getValueAt(tabla.getSelectedRow(), 0).toString(),farmacia);
                actualizarTabla();
            }
        } catch (Exception e) {
            System.out.println("error eliminar");
        }

    }//GEN-LAST:event_eliminarButtonMouseClicked

    private void tablaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tablaPropertyChange

        try {
            if (tabla.getSelectedRow() >= 0 && tabla.getSelectedColumn() > 0 && tabla.getSelectedColumn() != 3) {

                farmacia.getR_empleados().modificarEmpleado(tabla.getValueAt(tabla.getSelectedRow(), 0).toString(), tabla.getColumnName(tabla.getSelectedColumn()).toLowerCase(), tabla.getValueAt(tabla.getSelectedRow(), tabla.getSelectedColumn()).toString().toLowerCase());
            }
        } catch (Exception e) {
            System.out.println("error change");
        }

    }//GEN-LAST:event_tablaPropertyChange

    private void btnIngresarE1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresarE1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnIngresarE1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnIngresarE1;
    private javax.swing.JLabel eliminarButton;
    private javax.swing.JTextField inCodigo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
