/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Panels;

import static Gui.Menu.pnlPrincipal;
import Farmacia.Empleado;
import Farmacia.Farmacia;
import Farmacia.Medicamento;
import Farmacia.RegistroClientes;
import Gui.Menu;
import java.util.ArrayList;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kevin
 */
public class TomarPedido extends javax.swing.JPanel {

    //Lista de medicamentos
    DefaultListModel jlist = new DefaultListModel();
    //Lista de compras
    DefaultListModel listaVenta = new DefaultListModel();
    ArrayList<String> detalles = new ArrayList<String>();
    //Tipo de cliente por defecto
    //Pedido creado
    private boolean pedido = false;
    //validadores
    ArrayList<String> validador = new ArrayList<String>();
    //Contador para lista de venta
    int c = 0;

    Farmacia farmacia;
    Empleado actual;
    RegistroClientes registroClientes;
    Menu menu;

    public TomarPedido(Empleado actual, Farmacia farmacia, RegistroClientes registroClientes) {
        this.registroClientes = registroClientes;
        this.actual = actual;
        this.farmacia = farmacia;
        initComponents();
        jlist = new DefaultListModel();
        lista.setModel(jlist);
        listaVenta = new DefaultListModel();
        venta.setModel(listaVenta);
        validador.add("client");
        validador.add("00000000");
        obtenerLista(this.farmacia.getInventario().getMedicamentos());
    }

    public TomarPedido() {
        initComponents();
        jlist = new DefaultListModel();
        lista.setModel(jlist);
        listaVenta = new DefaultListModel();
        venta.setModel(listaVenta);
    }

    private void obtenerLista(ArrayList<Medicamento> medicamentos) {
        for (int i = 0; i < medicamentos.size(); i++) {
            jlist.addElement(medicamentos.get(i).getCodigo() + "    " + medicamentos.get(i).getNombre() + "    " + medicamentos.get(i).getCantidad() + "unid.    S/." + medicamentos.get(i).getPrecio());
        }
        if (medicamentos.isEmpty()) {
            jlist.addElement("No hay medicamentos registrados.");
        }
    }

    private void obtenerVenta(ArrayList<String> detalles) {
        c = 0;
        for (int i = 0; i < detalles.size(); i++) {
            listaVenta.addElement(detalles.get(i));
            c++;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        botonFactura = new javax.swing.JButton();
        botonClienteRegistrado = new javax.swing.JButton();
        botonBoleta = new javax.swing.JButton();
        botonNuevoCliente = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        venta = new javax.swing.JList<>();
        btnDelete = new javax.swing.JLabel();
        cancelButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(27, 37, 69));
        jPanel1.setMinimumSize(new java.awt.Dimension(700, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(700, 700));

        jPanel2.setBackground(new java.awt.Color(27, 37, 69));

        botonFactura.setBackground(new java.awt.Color(27, 37, 69));
        botonFactura.setForeground(new java.awt.Color(27, 37, 69));
        botonFactura.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_bill_100px.png"))); // NOI18N
        botonFactura.setBorder(null);
        botonFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonFacturaActionPerformed(evt);
            }
        });

        botonClienteRegistrado.setBackground(new java.awt.Color(27, 37, 69));
        botonClienteRegistrado.setForeground(new java.awt.Color(27, 37, 69));
        botonClienteRegistrado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_list_100px.png"))); // NOI18N
        botonClienteRegistrado.setBorder(null);
        botonClienteRegistrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonClienteRegistradoActionPerformed(evt);
            }
        });

        botonBoleta.setBackground(new java.awt.Color(27, 37, 69));
        botonBoleta.setForeground(new java.awt.Color(27, 37, 69));
        botonBoleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/icons8_bus_ticket_100px.png"))); // NOI18N
        botonBoleta.setBorder(null);
        botonBoleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBoletaActionPerformed(evt);
            }
        });

        botonNuevoCliente.setBackground(new java.awt.Color(27, 37, 69));
        botonNuevoCliente.setForeground(new java.awt.Color(27, 37, 69));
        botonNuevoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/farmaciav1/pkg1/imagenes/persona100.png"))); // NOI18N
        botonNuevoCliente.setBorder(null);
        botonNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonNuevoClienteActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NUEVO CLIENTE");

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CLIENTE REGISTRADO");

        jLabel6.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("BOLETA");

        jLabel7.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("FACTURA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(botonFactura)
                        .addGap(36, 36, 36)
                        .addComponent(botonBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 5, Short.MAX_VALUE)))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(botonClienteRegistrado)
                        .addGap(61, 61, 61)
                        .addComponent(botonNuevoCliente)
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)
                        .addGap(43, 43, 43))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonBoleta, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonNuevoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonClienteRegistrado, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonFactura, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOMAR PEDIDO");

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("MEDICAMENTOS");

        venta.setEnabled(false);
        jScrollPane3.setViewportView(venta);

        btnDelete.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnDelete.setText("ELIMINAR");
        btnDelete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnDelete.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        cancelButton.setText("Cancelar");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VENTA");

        lista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lista);

        btnAgregar.setFont(new java.awt.Font("Arial Narrow", 0, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        btnAgregar.setText("AGREGAR");
        btnAgregar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnAgregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(134, 134, 134))
                            .addComponent(btnAgregar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(292, 292, 292)
                        .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(6, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        if (c != 0) {
            actual.getPedido().eliminarProducto();
            listaVenta.clear();
            obtenerVenta(actual.getPedido().getDetalles());
            jlist.clear();
            obtenerLista(this.farmacia.getInventario().getMedicamentos());
        }
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnAgregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarMouseClicked
        // TODO add your handling code here:
        if (lista.getSelectedValue() != null) {
            if (!pedido) {

                if (validador.get(0).equals("persona")) {
                    actual.generarPedidoP(validador.get(1), lista.getSelectedValue().substring(0, 3), registroClientes);
                } else if (validador.get(0).equals("empresa")) {
                    actual.generarPedidoE(validador.get(1), lista.getSelectedValue().substring(0, 3), registroClientes);
                } else {
                    actual.generarPedidoP("00000000", lista.getSelectedValue().substring(0, 3), registroClientes);
                }
                pedido = true;
            } else {
                actual.getPedido().agregarProducto(lista.getSelectedValue().substring(0, 3));
            }
            listaVenta.clear();
            obtenerVenta(actual.getPedido().getDetalles());
            jlist.clear();
            obtenerLista(this.farmacia.getInventario().getMedicamentos());

        }
    }//GEN-LAST:event_btnAgregarMouseClicked

    private void botonNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoClienteActionPerformed
        // TODO add your handling code here:

        if (!pedido) {
            AgregarClienteTP agregarClienteTP = new AgregarClienteTP(registroClientes, validador);
            agregarClienteTP.setVisible(true);
//            System.out.println(validador.get(0));
        } else {
            AdvertenciaPedido advertencia = new AdvertenciaPedido(menu, true);
            advertencia.setVisible(true);
            System.out.println("Pedido en curso");
        }
    }//GEN-LAST:event_botonNuevoClienteActionPerformed

    private void botonClienteRegistradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonClienteRegistradoActionPerformed
        // TODO add your handling code here:

        if (!pedido) {
            registroClientes.actualizarListaEmpresas();
            registroClientes.actualizarListaPersonas();
            ClientesRegistradosTP clientesRegistrados = new ClientesRegistradosTP(registroClientes, validador);
            clientesRegistrados.setVisible(true);
//            System.out.println(validador.get(0));
        } else {
            AdvertenciaPedido advertencia = new AdvertenciaPedido(menu, true);
            advertencia.setVisible(true);
            System.out.println("Pedido en curso");
        }

    }//GEN-LAST:event_botonClienteRegistradoActionPerformed

    private void botonBoletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBoletaActionPerformed
        // TODO add your handling code here:
        if (listaVenta.getSize() > 0) {
            actual.getPedido().realizarVenta(actual.getPedido(), 0, false);
            actual.getPedido().getVenta().generarComprobante(farmacia, false);
            actual.registrarVenta(actual.getPedido().getVenta());
            //imprimir boleta
            actual.getPedido().getVenta().getBoleta().imprimir(farmacia, actual.getPedido().getVenta());
            cancelButton.doClick();
        }
    }//GEN-LAST:event_botonBoletaActionPerformed

    private void botonFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonFacturaActionPerformed
        // TODO add your handling code here:
        if (listaVenta.getSize() > 0) {
            actual.getPedido().realizarVenta(actual.getPedido(), 0, true);
            actual.getPedido().getVenta().generarComprobante(farmacia, true);
            actual.registrarVenta(actual.getPedido().getVenta());
            System.out.println("registrado en tp");
            //imprimir factura
            actual.getPedido().getVenta().getFactura().imprimir(farmacia, actual.getPedido().getVenta());
            cancelButton.doClick();
        }
    }//GEN-LAST:event_botonFacturaActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        for (int i = 0; i <= listaVenta.getSize(); i++) {
            if (c != 0) {
                actual.getPedido().eliminarProducto();
                listaVenta.clear();
                obtenerVenta(actual.getPedido().getDetalles());
                jlist.clear();
                obtenerLista(this.farmacia.getInventario().getMedicamentos());
            }
        }
        if (c != 0) {
            actual.getPedido().eliminarProducto();
            listaVenta.clear();
            obtenerVenta(actual.getPedido().getDetalles());
            jlist.clear();
            obtenerLista(this.farmacia.getInventario().getMedicamentos());
        }
        this.setVisible(false);

    }//GEN-LAST:event_cancelButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonBoleta;
    private javax.swing.JButton botonClienteRegistrado;
    private javax.swing.JButton botonFactura;
    private javax.swing.JButton botonNuevoCliente;
    private javax.swing.JLabel btnAgregar;
    private javax.swing.JLabel btnDelete;
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lista;
    private javax.swing.JList<String> venta;
    // End of variables declaration//GEN-END:variables
}
